gui:
  wrapLinesInStagingView: false
  showFileTree: false
  showNumstatInFilesView: true
  mainPanelSplitMode: "horizontal"
git:
  autoFetch: false
  localBranchSortOrder: recency
keybinding:
  prevBlock: <c-p>
  nextBlock: <c-n>
  createPatchOptionsMenu: ""
  toggleRangeSelect: V
